import{CITY_DATA,MODES,WEAPONS,createGame,updateForecast,riskForCity,applyCityAction,useWeapon,advanceTurn,nearestCity,bearingName,gradeGame}from'./engine.js';
let selectedMode='standard',game=null,turnAnimating=false;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function save(){if(game)localStorage.setItem('stc-save',JSON.stringify(game))}
function load(){try{return JSON.parse(localStorage.getItem('stc-save'))}catch{return null}}
function toast(msg){const el=$('#eventToast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function stormClass(w){if(w<63)return['熱帶風暴',1];if(w<118)return['強烈熱帶風暴',2];if(w<150)return['颱風',3];if(w<185)return['強颱風',4];if(w<250)return['超強颱風',5];return['滅世級風暴',6]}
function renderCities(){const layer=$('#cityLayer');layer.innerHTML='';game.cities.forEach(c=>{const risk=riskForCity(game,c);const b=document.createElement('button');b.className=`city-marker ${risk>72?'risk-high':''} ${c.status==='evacuating'?'evacuating':''} ${game.selectedCity===c.id?'selected':''}`;b.style.left=c.x+'%';b.style.top=c.y+'%';b.innerHTML=`<span>${c.name}<small>${c.pop}萬人 · 撤離${Math.round(c.evac)}%</small></span>`;b.onclick=()=>{game.selectedCity=c.id;renderAll();save()};layer.appendChild(b)})}
function renderResources(){const labels=[['people','👥','人員'],['supplies','📦','物資'],['fuel','⛽','燃料'],['power','⚡','電力'],['medical','✚','醫療包'],['energy','🔋','武器能源']];$('#resourceGrid').innerHTML=labels.map(([k,i,l])=>`<div class="resource-item"><span>${i}</span><small>${l}</small><b>${k==='power'||k==='energy'?Math.round(game.resources[k])+'%':Math.round(game.resources[k]).toLocaleString()}</b></div>`).join('')}
function renderWeapons(){const list=$('#weaponList');list.innerHTML='';game.weapons.forEach(w=>{const b=document.createElement('button');b.className=`weapon-card ${w.remaining?'cooldown':''}`;b.disabled=w.remaining>0||game.resources.energy<w.energy||game.ap<=0;b.innerHTML=`<div class="weapon-art">${w.icon}</div><b>${w.name}</b><small>能源 ${w.energy}% · 成功率 ${Math.round((w.success+(game.intel-.5)*.18)*100)}%</small><small>${w.desc}</small><span class="weapon-status">${w.remaining?`冷卻 ${w.remaining} 回合`:'部署就緒'}</span>`;b.onclick=()=>{const r=useWeapon(game,w.id);toast(r.msg);updateForecast(game);renderAll();save()};list.appendChild(b)})}
function renderImpact(){const points=game.storm.forecast;$('#impactTimeline').innerHTML=points.map((p,i)=>`<div class="impact-step ${i===2?'hot':''}"><span>${game.month}/${game.day+i+1}</span><b>${i===2?'⛈️':'🌧️'}</b><small>${i===2?'最大衝擊':'風險'}</small></div>`).join('');$('#lossBars').innerHTML=points.map((p,i)=>`<i style="height:${Math.max(8,90-Math.abs(i-2)*25)}%"></i>`).join('')}
function updatePath(){const f=game.storm.forecast;const start=game.storm;const end=f[f.length-1];const cp1={x:start.x-(start.x-end.x)*.34,y:start.y-(start.y-end.y)*.16};const cp2={x:start.x-(start.x-end.x)*.72,y:start.y-(start.y-end.y)*.66};$('#forecastPath').setAttribute('d',`M${start.x*10} ${start.y*6.8} C${cp1.x*10} ${cp1.y*6.8} ${cp2.x*10} ${cp2.y*6.8} ${end.x*10} ${end.y*6.8}`);const spread=12+(1-game.intel)*18;$('#forecastCone').setAttribute('d',`M${start.x*10} ${start.y*6.8} C${cp1.x*10} ${cp1.y*6.8} ${cp2.x*10} ${cp2.y*6.8} ${end.x*10} ${Math.max(0,(end.y-spread)*6.8)} L${end.x*10} ${Math.min(680,(end.y+spread)*6.8)} C${cp2.x*10} ${(cp2.y+spread*.5)*6.8} ${cp1.x*10} ${(cp1.y+spread*.2)*6.8} ${start.x*10} ${start.y*6.8}Z`);const hist=game.storm.history.map((p,i)=>(i?'L':'M')+p.x*10+' '+p.y*6.8).join(' ');$('#actualPath').setAttribute('d',hist)}
function renderStorm(){const s=game.storm;const el=$('#storm');const size=Math.max(135,Math.min(390,100+s.wind*.75));el.style.left=s.x+'%';el.style.top=s.y+'%';el.style.width=size+'px';el.style.height=size+'px';const [label,level]=stormClass(s.wind);$('#stormLevelBadge').textContent=`等級 ${level} ${label}`;$('#stormName').textContent=s.name;$('#stormCode').textContent=s.code;$('#windValue').textContent=Math.round(s.wind);$('#pressureValue').textContent=Math.round(s.pressure);$('#moveSpeedValue').textContent=Math.round(s.speed);$('#directionValue').textContent=bearingName(Math.cos(s.heading),Math.sin(s.heading));$('#radiusValue').textContent=Math.round(s.radius);$('#seaTempValue').textContent=s.seaTemp.toFixed(1)+'°C';const near=nearestCity(game);$('#riskValue').textContent=near.dist<10?'極高':near.dist<20?'高':'中等';$('#landfallTime').textContent=`${game.month}月${game.day+Math.max(1,Math.ceil(near.dist/7))}日 ${String((game.hour+9)%24).padStart(2,'0')}:00`;$('#livePosition').innerHTML=`<b>颱風實時位置</b><br>北緯 ${s.lat.toFixed(1)}°　東經 ${s.lng.toFixed(1)}°<br>最近城市：${near.city.name}（約 ${Math.round(near.dist*42)} km）<br>情報可信度：${Math.round(game.intel*100)}%`}
function renderAll(){if(!game)return;$('#gameDate').textContent=`${game.year} / ${game.month} / ${game.day}`;$('#gameTime').textContent=String(game.hour).padStart(2,'0')+':00';$('#turnLabel').textContent=game.turn;$('#genesisTime').textContent=`${game.year}/${game.month}/${game.day} 03:00`;$('#genesisPos').textContent=`北緯 ${game.storm.lat.toFixed(1)}° 東經 ${game.storm.lng.toFixed(1)}°`;$('#apValue').textContent=game.ap;$('#apMax').textContent=game.maxAp;$('#intelSummary').textContent=Math.round(game.intel*100)+'%';const city=game.cities.find(c=>c.id===game.selectedCity);$('#evacSummary').textContent=Math.round(city.evac)+'%';$('#defenseSummary').textContent=Math.round(city.defense)+'%';$('#supplySummary').textContent=Math.round(city.supplies)+'%';$('#endTurnButton').disabled=turnAnimating;renderCities();renderResources();renderWeapons();renderImpact();renderStorm();updatePath();$$('.phase').forEach((p,i)=>p.classList.toggle('active',i===Math.min(4,game.phase)))}
function start(seed,mode){game=createGame(seed,mode);updateForecast(game);showScreen('#gameScreen');renderAll();save()}
async function endTurn(){if(turnAnimating)return;turnAnimating=true;game.phase=3;renderAll();toast('部署鎖定，颱風開始自行移動…');const result=advanceTurn(game);await new Promise(r=>setTimeout(r,4100));turnAnimating=false;if(result.event)toast(result.event);if(game.gameOver){save();setTimeout(showResults,700)}else{game.phase=2;renderAll();save()}}
function showResults(){const r=gradeGame(game);$('#grade').textContent=r.grade;$('#resultTitle').textContent=r.title;$('#resultSummary').textContent=`風暴行動於第 ${game.turn-1} 回合結束。你在有限情報下完成了城市部署，最終總傷亡為 ${game.totalDeaths.toLocaleString()} 人。`;$('#resultMetrics').innerHTML=`<div><span>最終分數</span><b>${r.score}</b></div><div><span>平均撤離率</span><b>${r.avgEvac}%</b></div><div><span>平均防衛度</span><b>${r.avgDefense}%</b></div><div><span>基建損失</span><b>${game.totalDamage}</b></div>`;showScreen('#resultScreen')}
$$('.mode-card').forEach(b=>b.onclick=()=>{$$('.mode-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedMode=b.dataset.mode});$('#startButton').onclick=()=>start($('#seedInput').value||Date.now(),selectedMode);$('#continueButton').onclick=()=>{const s=load();if(!s){alert('暫時沒有可讀取的存檔');return}game=s;updateForecast(game);showScreen('#gameScreen');renderAll()};$$('[data-action]').forEach(b=>b.onclick=()=>{const r=applyCityAction(game,b.dataset.action);toast(r.msg);updateForecast(game);renderAll();save()});$('#endTurnButton').onclick=endTurn;$('#retryButton').onclick=()=>start(game.seed,game.modeKey);$('#menuButton').onclick=()=>showScreen('#homeScreen');
